package ru.andrewsalygin.graph.game.utils;

import org.newdawn.slick.SlickException;

public enum Flag {
    HIGHLIGHT_BUTTON,
    HIGHLIGHT_HOME_BUTTON,
    HIGHLIGHT_REPEAT_BUTTON,
    HIGHLIGHT_HELP_BUTTON,
    HIGHLIGHT_POWER_INCREASE_BUTTON,
    HIGHLIGHT_PROTECTION_INCREASE_BUTTON,
    HIGHLIGHT_REPLICATION_INCREASE_BUTTON,
    HIGHLIGHT_YES_BUTTON,
    HIGHLIGHT_NO_BUTTON,
    HIGHLIGHT_NODE,
    HIGHLIGHT_SEND_ALL_VIRUS,
    HIGHLIGHT_SEND_HALF_VIRUS,
    HIGHLIGHT_SEND_QUARTER_VIRUS,
    SELECTED_NODE_FROM_MOVE_VIRUS,
    SELECTED_NODE_TO_MOVE_VIRUS,
    MOVE_VIRUS_MODE,
    OPEN_HELP_MENU,
    REPEAT_GAME,
    EXIT_GAME
}
